project_name: layercake

release:
  github:
    owner: tommy351
    name: layercake

before:
  hooks:
    - go mod download

builds:
  - binary: layercake
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: .

archive:
  format: tar.gz
  name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - 'tommy351/layercake:{{ .Version }}'
      - 'tommy351/layercake:{{ .Major }}.{{ .Minor }}'
      - 'tommy351/layercake:{{ .Major }}'
      - 'tommy351/layercake:latest'
