language: go

go:
  - 1.11.x
  - master

env:
  - GO111MODULE=on

matrix:
  allow_failures:
    - go: master
  fast_finish: true

services:
  - docker

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.2

script:
  # Make sure go generate is run
  - go generate -v ./... && git diff --exit-code
  # Run tests
  - go test -v -race ./...
  # Run linters
  - golangci-lint run
