language: go

dist: xenial

go: 1.11.x

env:
  - GO111MODULE=on

services:
  - docker

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.2

before_script:
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

script:
  - make check_generated
  - make lint
  - make test
  - make test_examples/hello_world
  - make test_examples/hello_world BUILD_OPTIONS='--build-kit'

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
