[package]
name = "layercake"
version = "0.1.0"
authors = ["Tommy Chen <tommy351@gmail.com>"]

[dependencies]
clap = "2.32.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_yaml = "0.8.6"
serde_json = "1.0.32"
slog = "2.4.1"
sloggers = "0.3.1"
failure = "0.1.3"
tar = "0.4.17"
